name: Build test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      ignore: ${{ steps.filter.outputs.ignore-files }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ignore-files:
              - '**.md'
  build:
    environment: development
    needs: changes
    if: ${{ needs.changes.outputs.ignore-files == 'false' }}
    runs-on: ubuntu-latest
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Packages
        run: yarn install

      - name: Nextjs Build Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - name: Set .env
        run: echo "${{ secrets.PROJECT_ENV }}" > .env.local
      - name: Build Test
        run: yarn build
