name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      repo-settings: ${{ steps.filter.outputs.repo-settings }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            repo-settings:
              - '**/!(*.md)'
              - '!.github/**/*'
              - '!.husky/**/*'
              - '!.vscode/**/*'
  check:
    needs: changes
    if: ${{ needs.changes.outputs.repo-settings == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Packages
        run: yarn install --immutable

      - name: Check All
        run: yarn conc "yarn:lint" "yarn:typecheck" "yarn:stylelint"
