name: Development Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-app:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build-app
    environment: development
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Download Built App
        uses: actions/download-artifact@v3
        with:
          name: built-app
      - name: LS
        run: ls -al
      - name: Publish
        run: yarn dlx wrangler pages publish "out" --project-name "${{ secrets.CLOUDFLARE_PAGES_PROJECT_NAME }}" --commit-message " "
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
