name: Build project and run Lighthouse CI
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: yarn set version 3.2.0

      - name: Install Packages
        run: |
          yarn install

      - name: Build
        run: |
          yarn run build

      - name: Run Lighthouse CI
        run: |
          yarn add @lhci/cli@0.9.x
          yarn lighthouse --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
